### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by ManhVu99** [justsoft/video_thumbnail#122]
**Has anyone faced this issue before? How to solve it and why? Thank for your help .(Flutter 3.0, video_thumbnail ^0.5.2).**
**My code:**
![image](https://user-images.githubusercontent.com/101684724/181210884-df8832d3-9319-45e3-9e96-91e47e743f41.png)

**Debug console:**

V/MediaHTTPService(13238): MediaHTTPService(android.media.MediaHTTPService@5ced12e): Cookies: null
V/MediaHTTPService(13238): makeHTTPConnection: CookieManager created: java.net.CookieManager@45f44cf
V/MediaHTTPService(13238): makeHTTPConnection(android.media.MediaHTTPService@5ced12e): cookieHandler: java.net.CookieManager@45f44cf Cookies: null.
W/System.err(13238): java.lang.RuntimeException: setDataSource failed: status = 0x80000000
W/System.err(13238): 	at android.media.MediaMetadataRetriever._setDataSource(Native Method)
W/System.err(13238): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:272)
W/System.err(13238): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin.createVideoThumbnail(VideoThumbnailPlugin.java:219)
W/System.err(13238): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin.buildThumbnailData(VideoThumbnailPlugin.java:123)
W/System.err(13238): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin.buildThumbnailFile(VideoThumbnailPlugin.java:140)
W/System.err(13238): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin.access$000(VideoThumbnailPlugin.java:32)
W/System.err(13238): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin$1.run(VideoThumbnailPlugin.java:79)
W/System.err(13238): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(13238): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(13238): 	at java.lang.Thread.run(Thread.java:923)
E/flutter (13238): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method file on channel plugins.justsoft.xyz/video_thumbnail)

**Comment by krivir** [comment]
Any solution for this? I am facing the same.

**Comment by Bestfastfire** [comment]
Same here

**Comment by huzaifasaeed** [comment]
@justsoft please fix this error: 
"No implementation found for method file on channel plugins.justsoft.xyz/video_thumbnail"
