### ISSUE TITLE
Couldn't generate thumbnail, error:Error Domain=AVFoundationErrorDomain Code=-11800

### ISSUE THREAD

**Issue by ritvij14** [justsoft/video_thumbnail#130]
```dart
Uint8List? bytes = await VideoThumbnail.thumbnailData(
   video: doc["mediaUrl"],
   maxHeight: (MediaQuery.of(context).size.height * 0.25)
          .round(),
   maxWidth: (MediaQuery.of(context).size.width * 0.3).round(),
);
```

Trying the above code to get the thumbnail of a video stored in firebase whose URL is fetched from firestore.

Half of the times it works but rest of the times it fails, with the below error.

```bash
couldn't generate thumbnail, error:Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSLocalizedFailureReason=An unknown error occurred (-12792), NSLocalizedDescription=The operation could not be completed, NSUnderlyingError=0x2828ac720 {Error Domain=NSOSStatusErrorDomain Code=-12792 "(null)"}}

════════ Exception caught by image resource service ════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack
#0      _futurize (dart:ui/painting.dart:5886:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:5741:12)
#2      instantiateImageCodecFromBuffer (dart:ui/painting.dart:2092:60)
#3      PaintingBinding.instantiateImageCodecFromBuffer
package:flutter/…/painting/binding.dart:153
#4      MemoryImage._loadAsync
package:flutter/…/painting/image_provider.dart:1090
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════
```

![IMG_911F06E4ECB4-1](https://user-images.githubusercontent.com/51456744/201074131-39d97ccb-668c-4725-b701-faa8deb6d171.jpeg)

**Comment by Abdullatif-Eida** [comment]
The error "Couldn't generate thumbnail, error:Error Domain=AVFoundationErrorDomain Code=-11800" usually indicates that there is an issue with generating a thumbnail image for a video file. This can be caused by a variety of factors, such as a corrupt or unsupported video file, an issue with the device or operating system, or a problem with the code that is generating the thumbnail.

Here are a few things you can try to fix this issue:

Check the video file: Make sure the video file is not corrupt and is in a supported format. You can try playing the video file on a different device or in a different player to see if the issue is with the file itself.

Check the device and operating system: Make sure the device and operating system you are using are compatible with the video file and the code that is generating the thumbnail. You may need to update the device or operating system to the latest version to fix any compatibility issues.

Check the code: Make sure the code that is generating the thumbnail is correct and is not causing any errors. You can use the Flutter debugger or print statements to debug the code and see where the issue is occurring.

Check for permissions: Make sure you have the necessary permissions to access the video file and generate the thumbnail. On iOS, you may need to add the NSPhotoLibraryUsageDescription key to your app's Info.plist file to request access to the photo library.

**Comment by mogsten** [comment]
^ If this isn't a ChatGPT response, then I don't know what is hahaah

**Comment by tonypereiramelo** [comment]
Hi, I have the same problem on iOS: 

couldn't generate thumbnail, error:Error Domain=AVFoundationErrorDomain Code=-11832 "Cannot Open" UserInfo={NSLocalizedFailureReason=This media cannot be used., NSLocalizedDescription=Cannot Open, NSUnderlyingError=0x282f15440 {Error Domain=NSOSStatusErrorDomain Code=-12431 "(null)"}}

Any updates on the problem?

**Comment by heyallieson** [comment]
Hi, I have the same issue as well. Same error message as everyone above. 

But, I found out that it works if you pass in the literal url (ex. 'https://...') instead of a variable (ex. url). I checked if both values are the same and they are. But for some reason, the url string works but the variable returns the error message.

**Comment by elsayedz** [comment]
Any updates?

**Comment by mikkksa** [comment]
Comment strings where `imgGenerator.requestedTimeToleranceBefore` and `imgGenerator.requestedTimeToleranceBefore`  variables are set in your **VideoThumbnailPlugin.m** file from flutter pub sources. In my case this file is located in /Users/my_user/.pub-cache/hosted/pub.dev/video_thumbnail-<version>/ios/Classes

**Comment by Deepali-Rai** [comment]
> Hi, I have the same problem on iOS:
> 
> couldn't generate thumbnail, error:Error Domain=AVFoundationErrorDomain Code=-11832 "Cannot Open" UserInfo={NSLocalizedFailureReason=This media cannot be used., NSLocalizedDescription=Cannot Open, NSUnderlyingError=0x282f15440 {Error Domain=NSOSStatusErrorDomain Code=-12431 "(null)"}}
> 
> Any updates on the problem?

Did u resolve this?
