### ISSUE TITLE
not support avi video?

### ISSUE THREAD

**Issue by wengxianxun** [justsoft/video_thumbnail#132]
couldn't generate thumbnail, error:Error Domain=AVFoundationErrorDomain Code=-11869 "Cannot Open" UserInfo={NSLocalizedFailureReason=This media cannot be used., NSLocalizedDescription=Cannot Open, NSUnderlyingError=0x282c70210 {Error Domain=NSOSStatusErrorDomain Code=-12430 "(null)"}}
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(IO Error, Failed to write data to file, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
<asynchronous suspension>
#2      VideoThumbnail.thumbnailFile (package:video_thumbnail/video_thumbnail.dart:48:12)
<asynchronous suspension>
#3      _VideoEditorExampleState.getImage (package:example/main.dart:74:22)
<asynchronous suspension>

**Comment by NajamLodhi** [comment]
any solutions ?
