### ISSUE TITLE
VideoFrame is a NULL pointer

### ISSUE THREAD

**Issue by indeedshaw** [justsoft/video_thumbnail#148]
At first, I ignored the problem, thinking it was the video. However, as the number of videos increased, more and more videos appeared this problem, but in the Android native demo will not appear this problem.
Android natve demo, the same impl as plugin:
![S31009-16454095_com example mykotlinapplication-cut](https://github.com/justsoft/video_thumbnail/assets/119829832/2a624d9c-8ace-40fa-a640-10cfe3835557)

It's a weird question.
I rewrote a plugin with the same implementation and got the same result as the video_thumbnail plugin.
But, When I changed both places, the results became better:
![image](https://github.com/justsoft/video_thumbnail/assets/119829832/2761965c-197f-4d26-b86f-c744ef85fde4)

Although some videos still get this error, the result is still better than the beginning~.

Of course, if you do not care that the screenshot is anywhere in the video, you can set this:
`mediaMetadataRetriever.frameAtTime`

All in all, hopefully the plugin will be maintained!
@justsoft

**Comment by nuxwork** [comment]
I encountered the same problem.
```shell
E/AndroidRuntime(29443): FATAL EXCEPTION: FinalizerWatchdogDaemon E/AndroidRuntime(29443): Process:  
 com.example.camera, PID: 29443 E/AndroidRuntime(29443): java.util.concurrent.TimeoutException:  
 android.media.MediaMetadataRetriever.finalize() timed out after 10 seconds E/AndroidRuntime(29443): at  
  android.media.MediaMetadataRetriever.native_finalize(Native Method) E/AndroidRuntime(29443): at  
 android.media.MediaMetadataRetriever.finalize(MediaMetadataRetriever.java:332) E/AndroidRuntime(29443): at  
  java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222) E/AndroidRuntime(29443): at  
  java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209) E/AndroidRuntime(29443): at  
  java.lang.Thread.run(Thread.java:761) E/libEGL (29443): call to OpenGL ES API with no current context (logged once per  
 thread) E/MediaMetadataRetrieverJNI(29443): getFrameAtTime: videoFrame is a NULL pointer   
 E/MediaMetadataRetrieverJNI(29443): getFrameAtTime: videoFrame is a NULL pointer    
  E/MediaMetadataRetrieverJNI(29443): getFrameAtTime: videoFrame is a NULL pointer    
 E/MediaMetadataRetrieverJNI(29443): getFrameAtTime: videoFrame is a NULL pointer  
 E/MediaMetadataRetrieverJNI(29443): getFrameAtTime: videoFrame is a NULL pointer  
 E/MediaMetadataRetrieverJNI(29443): getFrameAtTime: videoFrame is a NULL pointer  
```

**Comment by Munsif-Ali** [comment]
Any Update on This Issue got the same Exception on flutter app and the App got crashed.

```
FATAL EXCEPTION: FinalizerWatchdogDaemon
E/AndroidRuntime(30927): Process: com.metasense.lqdcnvs_mobile, PID: 30927
E/AndroidRuntime(30927): java.util.concurrent.TimeoutException: android.media.MediaMetadataRetriever.finalize() timed out after 10 seconds
E/AndroidRuntime(30927): 	at android.media.MediaMetadataRetriever.native_finalize(Native Method)
E/AndroidRuntime(30927): 	at android.media.MediaMetadataRetriever.finalize(MediaMetadataRetriever.java:1127)
E/AndroidRuntime(30927): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:339)
E/AndroidRuntime(30927): 	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:324)
E/AndroidRuntime(30927): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:300)
E/AndroidRuntime(30927): 	at java.lang.Daemons$Daemon.run(Daemons.java:145)
E/AndroidRuntime(30927): 	at java.lang.Thread.run(Thread.java:1012)
I/Process (30927): Sending signal. PID: 30927 SIG: 9
Lost connection to device.
```
