### ISSUE TITLE
MissingPluginException(No implementation found for method file on channel plugins.justsoft.xyz/video_thumbnail)

### ISSUE THREAD

**Issue by VocsyAniket** [justsoft/video_thumbnail#161]
I'm get video from phone local storage, after get thumbnail file image.

```
VideoThumbnail Error ----- MissingPluginException(No implementation found for method file on channel plugins.justsoft.xyz/video_thumbnail)
VideoThumbnail Trace ----- #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      VideoThumbnail.thumbnailFile (package:video_thumbnail/video_thumbnail.dart:48:12)
<asynchronous suspension>
#2      getVideoThumbImage (package:sing_karaoke/constant.dart:103:19)
<asynchronous suspension>
#3      getVideoFromStorageAndroid (package:sing_karaoke/constant.dart:78:23)
<asynchronous suspension>
#4      MainScreen.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:sing_karaoke/UI/mainscreen.dart:108:75)
<asynchronous suspension>
#5      MainScreen.build.<anonymous closure>.<anonymous closure> (package:sing_karaoke/UI/mainscreen.dart:108:35)
<asynchronous suspension>
```

How to Solve this Issue ???

**Comment by partha-zoozle** [comment]
is there any solution for this?

**Comment by hayatshin** [comment]
I have the same issue

**Comment by VocsyAniket** [comment]
this issue video file in get thumbnail image (this video file path is phone local storage path)

solution below :

```

/// get thumbnail in file video path
String image = await getVideoThumbImage(videoPath);
 
 
getVideoThumbImage(videoPathUrl) async {
    try {
      String tempPath = (await getApplicationDocumentsDirectory()).path;
      String? image = await VideoThumbnail.thumbnailFile(
        video: videoPathUrl,
        thumbnailPath: tempPath,
        imageFormat: ImageFormat.JPEG,
        quality: 75,
      );
      return image ?? 'ERROR';
    } catch (e, t) {
      print('VideoThumbnail File Error ----- ${e}');
      print('VideoThumbnail File Trace ----- ${t}');
      return 'ERROR';
    }
}


/// show thumbnail image
Container(
                        decoration: BoxDecoration(                         
                            image: DecorationImage(image: FileImage(File(image), fit: BoxFit.cover)),          
                      ),
```

**Comment by VocsyAniket** [comment]
> is there any solution for this?

i have already send solution, check this below part

**Comment by VocsyAniket** [comment]
> I have the same issue

i have already send solution, check this below part

**Comment by 1MinuteAunty** [comment]
@VocsyAniket  which part are you talking about?
