### ISSUE TITLE
Error running pod install

### ISSUE THREAD

**Issue by yuefeng007** [justsoft/video_thumbnail#17]
```
bogon:demo a$ flutter run
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...                                             81.8s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A video_thumbnail
      - Flutter
      - amap_core_fluttify
      - amap_location_fluttify
      - city_pickers
      - flutter_plugin_android_lifecycle
      - flutter_sound
      - flutter_splash_screen
      - fluttertoast
      - foundation_fluttify
      - image_crop
      - image_picker
      - path_provider
      - path_provider_macos
      - permission_handler
      - shared_preferences
      - shared_preferences_macos
      - shared_preferences_web
      - tencent_im_plugin
      - webview_flutter

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `amap_core_fluttify` from
    `.symlinks/plugins/amap_core_fluttify/ios`
    -> Fetching podspec for `amap_location_fluttify` from
    `.symlinks/plugins/amap_location_fluttify/ios`
    -> Fetching podspec for `city_pickers` from
    `.symlinks/plugins/city_pickers/ios`
    -> Fetching podspec for `flutter_plugin_android_lifecycle` from
    `.symlinks/plugins/flutter_plugin_android_lifecycle/ios`
    -> Fetching podspec for `flutter_sound` from
    `.symlinks/plugins/flutter_sound/ios`
    -> Fetching podspec for `flutter_splash_screen` from
    `.symlinks/plugins/flutter_splash_screen/ios`
    -> Fetching podspec for `fluttertoast` from
    `.symlinks/plugins/fluttertoast/ios`
    -> Fetching podspec for `foundation_fluttify` from
    `.symlinks/plugins/foundation_fluttify/ios`
    -> Fetching podspec for `image_crop` from `.symlinks/plugins/image_crop/ios`
    -> Fetching podspec for `image_picker` from
    `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `path_provider` from
    `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `path_provider_macos` from
    `.symlinks/plugins/path_provider_macos/ios`
    -> Fetching podspec for `permission_handler` from
    `.symlinks/plugins/permission_handler/ios`
    -> Fetching podspec for `shared_preferences` from
    `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `shared_preferences_macos` from
    `.symlinks/plugins/shared_preferences_macos/ios`
    -> Fetching podspec for `shared_preferences_web` from
    `.symlinks/plugins/shared_preferences_web/ios`
    -> Fetching podspec for `tencent_im_plugin` from
    `.symlinks/plugins/tencent_im_plugin/ios`
    -> Fetching podspec for `video_thumbnail` from
    `.symlinks/plugins/video_thumbnail/ios`
    -> Fetching podspec for `webview_flutter` from
    `.symlinks/plugins/webview_flutter/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_8_f_f.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/8/f/f/AMapFoundation/1.6.2/AMapFoundation.podspec.json exists!
      Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_0_3_9.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/0/3/9/AMapLocation/2.6.4/AMapLocation.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_6_1_0.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/6/1/0/TXIMSDK_iOS/4.6.102/TXIMSDK_iOS.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_8_d_3.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/8/d/3/HandyJSON/5.0.2-beta/HandyJSON.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_1_9_2.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/9/2/libwebp/1.1.0/libwebp.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/8/f/f/AMapFoundation/1.6.2/AMapFoundation.podspec.json exists!
      Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/0/3/9/AMapLocation/2.6.4/AMapLocation.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/8/f/f/AMapFoundation/1.6.2/AMapFoundation.podspec.json exists!
      Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/6/1/0/TXIMSDK_iOS/4.6.102/TXIMSDK_iOS.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/8/d/3/HandyJSON/5.0.1/HandyJSON.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/9/2/libwebp/1.1.0/libwebp.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/1/9/2/libwebp/1.1.0-rc2/libwebp.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/9/2/libwebp/1.0.3/libwebp.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/9/2/libwebp/1.0.2/libwebp.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/9/2/libwebp/1.0.1/libwebp.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/9/2/libwebp/1.0.0/libwebp.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/9/2/libwebp/0.6.1/libwebp.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/9/2/libwebp/0.6.0/libwebp.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/9/2/libwebp/0.5.2/libwebp.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/9/2/libwebp/0.5.1/libwebp.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/9/2/libwebp/0.5.0/libwebp.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/9/2/libwebp/0.4.4/libwebp.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/9/2/libwebp/0.4.3/libwebp.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/9/2/libwebp/0.4.2/libwebp.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/9/2/libwebp/0.4.1/libwebp.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/9/2/libwebp/1.1.0/libwebp.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/9/2/libwebp/1.1.0/libwebp.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/9/2/libwebp/1.1.0/libwebp.podspec.json
      exists! Returning local because checking is only perfomed in repo update

    Comparing resolved specification to the sandbox manifest
      A AMapFoundation
      A AMapLocation
      A Flutter
      A HandyJSON
      A TXIMSDK_iOS
      A amap_core_fluttify
      A amap_location_fluttify
      A city_pickers
      A flutter_plugin_android_lifecycle
      A flutter_sound
      A flutter_splash_screen
      A fluttertoast
      A foundation_fluttify
      A image_crop
      A image_picker
      A libwebp
      A path_provider
      A path_provider_macos
      A permission_handler
      A shared_preferences
      A shared_preferences_macos
      A shared_preferences_web
      A tencent_im_plugin
      A video_thumbnail
      A webview_flutter

    Downloading dependencies

    -> Installing AMapFoundation (1.6.2)
      > Copying AMapFoundation from
      `/Users/a/Library/Caches/CocoaPods/Pods/Release/AMapFoundation/1.6.2-672dc
      ` to `Pods/AMapFoundation`

    -> Installing AMapLocation (2.6.4)
      > Copying AMapLocation from
      `/Users/a/Library/Caches/CocoaPods/Pods/Release/AMapLocation/2.6.4-b4162`
      to `Pods/AMapLocation`

    -> Installing Flutter (1.0.0)

    -> Installing HandyJSON (5.0.1)
      > Copying HandyJSON from
      `/Users/a/Library/Caches/CocoaPods/Pods/Release/HandyJSON/5.0.1-d45b8` to
      `Pods/HandyJSON`

    -> Installing TXIMSDK_iOS (4.6.102)
      > Copying TXIMSDK_iOS from
      `/Users/a/Library/Caches/CocoaPods/Pods/Release/TXIMSDK_iOS/4.6.102-e2f69`
      to `Pods/TXIMSDK_iOS`

    -> Installing amap_core_fluttify (0.0.1)

    -> Installing amap_location_fluttify (0.0.1)

    -> Installing city_pickers (0.0.1)

    -> Installing flutter_plugin_android_lifecycle (0.0.1)

    -> Installing flutter_sound (0.0.1)

    -> Installing flutter_splash_screen (0.0.1)

    -> Installing fluttertoast (0.0.2)

    -> Installing foundation_fluttify (0.0.1)

    -> Installing image_crop (0.0.1)

    -> Installing image_picker (0.0.1)

    -> Installing libwebp (1.1.0)
     > Git download
     > Git download
         $ /usr/bin/git clone https://chromium.googlesource.com/webm/libwebp
         /var/folders/sx/8_znzqcs1v9_cs8znzclz0p40000gn/T/d20200317-60958-ut8hwc
         --template= --single-branch --depth 1 --branch v1.1.0

    [!] Error installing libwebp
    [!] /usr/bin/git clone https://chromium.googlesource.com/webm/libwebp
    /var/folders/sx/8_znzqcs1v9_cs8znzclz0p40000gn/T/d20200317-60958-ut8hwc
    --template= --single-branch --depth 1 --branch v1.1.0

    Cloning into
    '/var/folders/sx/8_znzqcs1v9_cs8znzclz0p40000gn/T/d20200317-60958-ut8hwc'...
    fatal: unable to access 'https://chromium.googlesource.com/webm/libwebp/':
    Failed to connect to chromium.googlesource.com port 443: Operation timed out

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader.rb:14
    2:in `rescue in execute_command'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader.rb:13
    9:in `execute_command'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-downloader-1.2.2/lib/cocoapods-downl
    oader/base.rb:154:in `block in executable'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-downloader-1.2.2/lib/cocoapods-downl
    oader/git.rb:79:in `block in clone'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader.rb:17
    3:in `block in ui_sub_action'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.r
    b:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader.rb:17
    2:in `ui_sub_action'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-downloader-1.2.2/lib/cocoapods-downl
    oader/git.rb:77:in `clone'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-downloader-1.2.2/lib/cocoapods-downl
    oader/git.rb:45:in `download!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-downloader-1.2.2/lib/cocoapods-downl
    oader/base.rb:82:in `block in download'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader.rb:15
    7:in `block in ui_action'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.r
    b:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader.rb:15
    6:in `ui_action'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-downloader-1.2.2/lib/cocoapods-downl
    oader/base.rb:80:in `download'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader.rb:10
    8:in `download_source'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader.rb:75
    :in `download_request'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader/cache
    .rb:171:in `download'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader/cache
    .rb:154:in `block in uncached_pod'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader/cache
    .rb:181:in `in_tmpdir'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader/cache
    .rb:153:in `uncached_pod'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader/cache
    .rb:33:in `download_pod'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/downloader.rb:42
    :in `download'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/pod_so
    urce_installer.rb:117:in `download_source'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/pod_so
    urce_installer.rb:69:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:557
    :in `install_source_of_pod'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:508
    :in `block (2 levels) in install_pod_sources'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.r
    b:86:in `titled_section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:507
    :in `block in install_pod_sources'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:490
    :in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:490
    :in `install_pod_sources'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:249
    :in `block in download_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.r
    b:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:248
    :in `download_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:157
    :in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.
    rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in
    `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in
    `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top
    (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳
         Cloning into
         '/var/folders/sx/8_znzqcs1v9_cs8znzclz0p40000gn/T/d20200317-60958-ut8hw
         c'...
         fatal: unable to access
         'https://chromium.googlesource.com/webm/libwebp/': Failed to connect to
         chromium.googlesource.com port 443: Operation timed out

    [!] 'AMapFoundation' uses the unencrypted 'http' protocol to transfer the
    Pod. Please be sure you're in a safe network with only trusted hosts.
    Otherwise, please reach out to the library author to notify them of this
    security issue.

    [!] 'AMapLocation' uses the unencrypted 'http' protocol to transfer the Pod.
    Please be sure you're in a safe network with only trusted hosts. Otherwise,
    please reach out to the library author to notify them of this security
    issue.

Error running pod install
Error launching application on iPhone 11 Pro Max.
```

**Comment by yuefeng007** [comment]
```
homepage: https://developers.google.com/speed/webp/=>https://github.com/webmproject/
git:"https://chromium.googlesource.com/webm/libwebp=>https://github.com/webmproject/libwebp.git"
```

**Comment by zhjangbolin** [comment]
How to change the downloadLinks?I have the same problem too.

**Comment by llt3677** [comment]
me too, how to solve it
