### ISSUE TITLE
E/MediaMetadataRetriever: setDataSource - FileNotFoundException (on Samsung)

### ISSUE THREAD

**Issue by dheeraj2dj** [justsoft/video_thumbnail#31]
Error while generating thumbnail, especially on Samsung phones!

The one am testing is a Samsung M30s. Please help with the following error. Many of my users are having this issue! ☹️ 

```
D/ThumbnailPlugin(23668): buildThumbnailData( format:0, maxh:0, maxw:500, timeMs:0, quality:70 )
E/MediaMetadataRetriever(23668): setDataSource - FileNotFoundException
W/System.err(23668): java.lang.IllegalArgumentException
W/System.err(23668): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:85)
W/System.err(23668): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin.createVideoThumbnail(VideoThumbnailPlugin.java:201)
W/System.err(23668): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin.buildThumbnailData(VideoThumbnailPlugin.java:116)
W/System.err(23668): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin.access$100(VideoThumbnailPlugin.java:37)
W/System.err(23668): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin$1.run(VideoThumbnailPlugin.java:77)
W/System.err(23668): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(23668): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(23668): 	at java.lang.Thread.run(Thread.java:919)
I/flutter (23668): MissingPluginException(No implementation found for method data on channel video_thumbnail)
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.5 19F101, locale en-IN)
    • Flutter version 1.17.2 at /Users/dheeraj2dj/flutter
    • Framework revision 5f21edf8b6 (6 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dheeraj2dj/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • SM M307F • RZ8M844J4SR • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```
</details>

**Comment by justsoft** [comment]
Please make sure the video file exists and has sufficient privilegs for reading.
