### ISSUE TITLE
Get the video thumbnail error

### ISSUE THREAD

**Issue by lan2000** [justsoft/video_thumbnail#82]
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 2020.3)
[✓] Connected device (1 available)

ipad -14.7.1

Get the video thumbnail error：
couldn't generate thumbnail, error:Error Domain=AVFoundationErrorDomain Code=-11832 "Cannot Open" UserInfo={NSLocalizedFailureReason=This media cannot be used., NSLocalizedDescription=Cannot Open, NSUnderlyingError=0x2810c7c00 {Error Domain=NSOSStatusErrorDomain Code=-12431 "(null)"}}

**Comment by lan2000** [comment]
The first time to get the picture is successful, the second time it fails.

**Comment by lan2000** [comment]
The video is in the cache path of the app

**Comment by lan2000** [comment]
Stable versions of video_thumbnail ： 0.4.3

**Comment by justsoft** [comment]
1) Make sure the second video is readable, before call the thumbnail function, try to read the content from the video file.
2) Use the thumbnailData instead of thumbnailFile to see any difference.

**Comment by lan2000** [comment]
It has been confirmed that the video is readable, and the video can be played directly
An error is reported when thumbnailFile:

couldn't generate thumbnail, error:Error Domain=AVFoundationErrorDomain Code=-11832 "Cannot Open" UserInfo={NSLocalizedFailureReason=This media cannot be used., NSLocalizedDescription=Cannot Open, NSUnderlyingError=0x283b15260 {Error Domain=NSOSStatusErrorDomain Code=-12431 "(null)"}}
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(IO Error, Failed to write data to file, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      VideoThumbnail.thumbnailFile (package:video_thumbnail/video_thumbnail.dart:44:12)
<asynchronous suspension>
#3      _TrimmerViewPageState.build.<anonymous closure> (package:video_thumbnail_example/trimmer_view_page.dart:194:38)
<asynchronous suspension>

**Comment by lan2000** [comment]
> 1. Make sure the second video is readable, before call the thumbnail function, try to read the content from the video file.
> 2. Use the thumbnailData instead of thumbnailFile to see any difference.

It has been confirmed that the video is readable, and the video can be played directly
An error is reported when thumbnailFile:

couldn't generate thumbnail, error:Error Domain=AVFoundationErrorDomain Code=-11832 "Cannot Open" UserInfo={NSLocalizedFailureReason=This media cannot be used., NSLocalizedDescription=Cannot Open, NSUnderlyingError=0x283b15260 {Error Domain=NSOSStatusErrorDomain Code=-12431 "(null)"}}
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(IO Error, Failed to write data to file, null, null)
#0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
#1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)

#2 VideoThumbnail.thumbnailFile (package:video_thumbnail/video_thumbnail.dart:44:12)

#3 _TrimmerViewPageState.build. (package:video_thumbnail_example/trimmer_view_page.dart:194:38)

**Comment by justsoft** [comment]
> > 1. Make sure the second video is readable, before call the thumbnail function, try to read the content from the video file.
> > 2. Use the thumbnailData instead of thumbnailFile to see any difference.
> 
> It has been confirmed that the video is readable, and the video can be played directly
> An error is reported when thumbnailFile:
> 
> couldn't generate thumbnail, error:Error Domain=AVFoundationErrorDomain Code=-11832 "Cannot Open" UserInfo={NSLocalizedFailureReason=This media cannot be used., NSLocalizedDescription=Cannot Open, NSUnderlyingError=0x283b15260 {Error Domain=NSOSStatusErrorDomain Code=-12431 "(null)"}}
> [VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(IO Error, Failed to write data to file, null, null)
> #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
> #1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
> 
> #2 VideoThumbnail.thumbnailFile (package:video_thumbnail/video_thumbnail.dart:44:12)
> 
> #3 _TrimmerViewPageState.build. (package:video_thumbnail_example/trimmer_view_page.dart:194:38)

So, the thumbnailData works? Only the thumbnailFile failed, right?
Check your iOS external storage write permission. Also switch to use the thumbnailData then write the data into file by yourself.

**Comment by lan2000** [comment]
Both thumbnailFile and thumbnailData have the same error.
I have checked the storage permissions.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "John ***@***.***&gt;; 
发送时间: 2021年8月18日(星期三) 中午11:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [justsoft/video_thumbnail] Get the video thumbnail error (#82)





    
Make sure the second video is readable, before call the thumbnail function, try to read the content from the video file.
 
Use the thumbnailData instead of thumbnailFile to see any difference.
   
It has been confirmed that the video is readable, and the video can be played directly
 An error is reported when thumbnailFile:
 
couldn't generate thumbnail, error:Error Domain=AVFoundationErrorDomain Code=-11832 "Cannot Open" UserInfo={NSLocalizedFailureReason=This media cannot be used., NSLocalizedDescription=Cannot Open, NSUnderlyingError=0x283b15260 {Error Domain=NSOSStatusErrorDomain Code=-12431 "(null)"}}
 [VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(IO Error, Failed to write data to file, null, null)
 #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
 #1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
 
#2 VideoThumbnail.thumbnailFile (package:video_thumbnail/video_thumbnail.dart:44:12)
 
#3 _TrimmerViewPageState.build. (package:video_thumbnail_example/trimmer_view_page.dart:194:38)
  
So, the thumbnailData works? Only the thumbnailFile failed, right?
 Check your iOS external storage write permission. Also switch to use the thumbnailData then write the data into file by yourself.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by justsoft** [comment]
Try to use ffmpeg to convert to another format of the video or different color space to see any difference?

**Comment by behlsoft** [comment]
facing same issue.. 1st time it works fine but second time it fails...

**Comment by sadaqatdev** [comment]
why this issue is close , it still occurring in latest version of package

**Comment by justsoft** [comment]
Please check out the new 0.5.0 version. Thanks.

**Comment by haozi5460** [comment]
> facing same issue.. 1st time it works fine but second time it fails...

The same issue  1st time it works fine but second time it fails...  V0.5.0

**Comment by justsoft** [comment]
Please provide me an URL which I can repro this issue.
Thanks
